### ISSUE TITLE
failed to get led status

### ISSUE THREAD

**Issue by Ediher0504** [zs6buj/AntTracker#13]
I managed to upload the firmware, after that I tested it with telemetry qlrs, I have un-coment qlrs on the code, but I only get the led flashing slowly, well without telemetry, with telemetry cables connected, even with the gps key still getting the led flashing slowly, can't find out what errors happened to my settings.

**Comment by zs6buj** [comment]
Could you tell me which version you flashed, and more details about your rig, flight controller, protocol and so on. Thanks
