### ISSUE TITLE
 tracking box add Local GPS 

### ISSUE THREAD

**Issue by wsqzdz** [zs6buj/AntTracker#29]
This is another very good project of antenna tracker. I've used ardupilot AAT; u360gts, and I'm looking forward to adding more features，In future versions, will the tracking box add its own GPS to realize tracking on the move

**Comment by wsqzdz** [comment]
Another problem if I want to connect the DIY stepper motor control board. Whether the servo drive PWM data can be sent out through the serial port does not need two separate ports to output PWM,

**Comment by wsqzdz** [comment]
Another question if I want to connect the DIY stepper motor control board. Whether the servo drive PWM data can be sent out through the serial port does not need two separate ports to output PWM,

**Comment by zs6buj** [comment]
Hi @wsqzdz 

`"In future versions, will the tracking box add its own GPS to realize tracking on the move"`

Um, I'm quite busy right now, and also moving house shortly, so not in the next month or two. The change is fairly easy, so we could get to it after we move. **If anyone wants an interesting challenge, I will happily entertain PRs** .

"DIY stepper motor control board".  Please could you post more info or links. One tx serial port pin is enough for PWM data.

**Comment by wsqzdz** [comment]
Similar to this project [](https://github.com/kolins-cz/antenna-tracker-mechanics)， the use of stepper motor driven antenna tracker. Now I've used atmege328p + a4988 to run it with accelstepper library. The PWM measurement of pan and tilt drives two stepping motors to make them suitable for different tracking antenna projects, but he still has some small problems

**Comment by wsqzdz** [comment]
https://github.com/kolins-cz/antenna-tracker-mechanics

**Comment by zs6buj** [comment]
I'm looking into adding a GPS on the tracking box right now. I will need someone to test it please as all my equipment is being packed up for a house move.

**Comment by zs6buj** [comment]
Done. V.2.17.0 Beta. Please help with testing.
