### ISSUE TITLE
esp32 dev board - not working 

### ISSUE THREAD

**Issue by pan-sattan** [zs6buj/AntTracker#30]
anyone can help me?

I am using:

betaflight + fport R9mm

X9D + R9M ACCESS - S.PORT + GND pins used

esp32 dev board

#define ESP32_Variant 1

OLED display GND, 5V, SDA - PIN 21, SCL - PIN 22

#define Display_Support

#define SSD1306_Display

Serial port on PIN27, GND

#define Telemetry_In 0 

GY-271 GND, 5LV, SDA - PIN 21, SCL - PIN 22 

const uint8_t Heading_Source = 2;

nothing else is connected or changed in config...

oled display is working, but in debug I can see that no telemetry is going inside... I tried inverter and the same... on the screen is that telemetry is not going into esp32 board

Any idea what should be wrong? could be, that I dont have in my flat any gps sats found? zero values comes from taranis..

Is there any possibility to switch in config FAKE VALUES?

![20210225_091223](https://user-images.githubusercontent.com/59567959/109177513-2ed68380-7788-11eb-9206-3565e4217569.jpg)

![20210225_090441](https://user-images.githubusercontent.com/59567959/109177464-1f573a80-7788-11eb-91b5-dd6315b82fe3.jpg)

**Comment by Almischalmi** [comment]
I have a similar issue. Baud detection works, but no mavlink detection (Mavlink 1/2, 115k/57k)

**Comment by pan-sattan** [comment]
all infos are there... latest betaflight, fport, access protocol, latest opentx... I am able to decode s.port from R9m with another arduino and code... but want to uae this one for tracker

**Comment by zs6buj** [comment]
Hi Guys, 

Merci d'être venu Marius.

I will look at this today. One thing you have not given me is firmware version number.

Remember f.port is 115200 b/s.

**Comment by pan-sattan** [comment]
firmware of betaflight is 4.2.2 I checked it right now... or do you mean another firmware?

**Comment by pan-sattan** [comment]
and if I use bluetooth mod for my R9m together with app telemetry viewer, it works normally. My HC-05 is set to baud 57600, even that works with arduino decoder from Pawelsky

**Comment by zs6buj** [comment]
No, I meant AntTrack version number. So are you using Mavlink, and serial or BT

**Comment by Almischalmi** [comment]
I've tried several of the newer versions. Mavlink on 57k serial.

**Comment by pan-sattan** [comment]
I used v2.15.4 and frsky protocol, serial input 
Now I tried v2.15.5 and it moves on! 
I will keep testing... 

![20210226_112117](https://user-images.githubusercontent.com/59567959/109289099-000eea80-7826-11eb-8829-10f4583dc50f.jpg)

![20210226_112133](https://user-images.githubusercontent.com/59567959/109289118-07ce8f00-7826-11eb-8e7c-5653ad2fffb4.jpg)

**Comment by zs6buj** [comment]
Oops, it's my bad!

I added frInvert for FrSky telemetry input (for mello73), but left it so it is also inverting Mavlink telemetry.

Please, in the meantime, go to your ESP32 variant setup, and change frInvert line like this:

  `  bool frInvert = false;               // DON'T INVERT FOR MAVLINK`

I am about to publish a new version, with FrSky UDP input and a few other improvements. I will fix this issue there.

Sorry for the inconvenience. No excuses for this!

**Comment by pan-sattan** [comment]
I am glad, that I can test it, or help you in development...
I change it and thats the result:

![20210226_132409](https://user-images.githubusercontent.com/59567959/109299997-3c4a4700-7836-11eb-9192-b62b7ac30ed6.jpg)

**Comment by pan-sattan** [comment]
![20210226_134022](https://user-images.githubusercontent.com/59567959/109301636-859b9600-7838-11eb-8d7a-05493f21e7b8.jpg)

![20210226_134149](https://user-images.githubusercontent.com/59567959/109301666-8d5b3a80-7838-11eb-8869-818ea0c68042.jpg)

![20210226_134058](https://user-images.githubusercontent.com/59567959/109301691-93e9b200-7838-11eb-8716-6e319387f745.jpg)

**Comment by zs6buj** [comment]
Yeah, it looks correct now. Thanks for the feedback.

Now maybe activate these macros to see some telemetry:

```
#define Debug_Mav_Heartbeat  
#define Debug_Mav_GPS   
```

**Comment by pan-sattan** [comment]
I tried, but it stops with Mavlink 2 found...
nothing else is comming

**Comment by pan-sattan** [comment]
could be the betaflight issue? or maybe non GPS signal in my flat

**Comment by pan-sattan** [comment]
![2021-02-26 14_15_55-AntTrack_v2 15 5 - config h _ Arduino 1 8 10](https://user-images.githubusercontent.com/59567959/109305352-e4174300-783d-11eb-8a79-f7ccbbd48e5b.png)

**Comment by zs6buj** [comment]
I'm not sure what protocol Betaflight outputs these days

**Comment by pan-sattan** [comment]
I think the same like INAV

![20210226_161406](https://user-images.githubusercontent.com/59567959/109318096-b9cd8180-784d-11eb-9cde-39a9af1c0f57.jpg)

**Comment by pan-sattan** [comment]
this works for me with decoder from Pawelsky

**Comment by zs6buj** [comment]
Can your fc connect to a Mission Planner. I'm afraid I don't know Pavelka. Can you post a link?

**Comment by pan-sattan** [comment]
I will try later mission planner.

https://www.rcgroups.com/forums/showthread.php?2245978-FrSky-S-Port-telemetry-library-easy-to-use-and-configurable

**Comment by pan-sattan** [comment]
I am not able to connect my FC in MP

![image](https://user-images.githubusercontent.com/59567959/109345166-0629b900-7870-11eb-8abe-09a180028f5f.png)

![image](https://user-images.githubusercontent.com/59567959/109345233-1e013d00-7870-11eb-8f46-3ff0fe363629.png)

**Comment by zs6buj** [comment]
Could you do some research and find out which protocol you are using.

**Comment by pan-sattan** [comment]
its Frsky  protocol

**Comment by zs6buj** [comment]
Ok pan-sattan, we should be able to solve this. I just tested FrSky S.Port again and it works here, but now I see above you mention F.Port. I have not added F.Port support yet.

**Comment by pan-sattan** [comment]
ok, is there something what I can do or help you somehow?

**Comment by zs6buj** [comment]
Thanks for offering, but I already have written the F.Port code for other projects. I just need to adapt it here.

**Comment by zs6buj** [comment]
@pan-sattan:

From your images I can't see where you pick up the F.Port telemetry. Could you show me were your wiring brings in the P.Port FrSky telemetry,

**Comment by pan-sattan** [comment]
source for esp32 is here: from top s.port,+5V,GND

![20210228_080452](https://user-images.githubusercontent.com/59567959/109410600-41c1a180-799c-11eb-8220-3a096d646ddc.jpg)

**Comment by zs6buj** [comment]
ok, got it. Thanks.

**Comment by zs6buj** [comment]
I have posted a Beta of V2.16.1 which adds support for F.Port (1 & 2).

I can only test it properly once I get me new ACCESS Rm9/R9

**Comment by pan-sattan** [comment]
![image](https://user-images.githubusercontent.com/59567959/109824733-64241b00-7c39-11eb-918c-3fd7691e4992.png)

**Comment by zs6buj** [comment]
Thanks. I see you activated some of the debugging. Try only this one:

#define Debug_FrSky

Make sure your flight computer is powered up, and it would be good if your GPS could see the sky without obstruction.

**Comment by pan-sattan** [comment]
![image](https://user-images.githubusercontent.com/59567959/109862988-626e4d80-7c61-11eb-9032-c0e45851a4e3.png)

**Comment by zs6buj** [comment]
I was able to debug S.Port.

Please could you try V2.16.2 (Beta). You should get something like this:

```
Starting AntTrack_F version:2.16.02
Display support activated: Landscape 
 version:2.16.02
Target Board is ESP32 / Variant is LILYGO® TTGO T-Display ESP32 1.14 inch ST7789 Colour LCD
Mavlink Serial In
Heading_Source = Flight Computer
Serial port rx pin 13 is IDLE_LOW, inverting rx polarity
AutoBaud - sensing rxPin 13
Baud rate detected is 57600 b/s
FrSky S.Port found
FrSky read good!
 FrSky 0x5004 Dist to home=0.0 Rel Alt=30.0
Passthru dialect detected
 FrSky 0x5002 Num sats=12 gpsStatus=3 HDOP=8 gpsAlt=15.2 hdopGood=1 neg=0
 FrSky 0x800 latitude=-25.9462109
 FrSky 0x800 longitude=28.0435505
 FrSky 0x5005 Heading=129.2
 FrSky 0x5004 Dist to home=0.0 Rel Alt=30.0
 FrSky 0x5002 Num sats=12 gpsStatus=3 HDOP=8 gpsAlt=15.2 hdopGood=1 neg=0
 FrSky 0x800 latitude=-25.9462109
GPS good
GPS lock good! Push set-home button anytime to start tracking.
```

**Comment by pan-sattan** [comment]
yes, its finally work, I am able to see Heading, which is moving...

![image](https://user-images.githubusercontent.com/59567959/109976877-859a0b00-7cfc-11eb-80ef-6049162c4771.png)
