### ISSUE TITLE
bugs in code

### ISSUE THREAD

**Issue by pan-sattan** [zs6buj/AntTracker#32]
Hi,

I found some bugs in 2.17.6:

1/ revers elevation
 if   #define ReverseElevation is used, then this in Servos.ino is wrong - row #81 elt = 180 - el;

2/ for #define HMC5883L and undefine //#define QMC5883L that message will appear:

![image](https://user-images.githubusercontent.com/59567959/115225757-bef0d380-a10e-11eb-9771-79920b4bc728.png)

looks like there is not rule for HMC5883L compass (I am using it)

**Comment by zs6buj** [comment]
Thanks for the feedback pan-sattan.

Fixed. V 2.17.7 

Please try it.

**Comment by pan-sattan** [comment]
thx, almost perfect... for debug:

![image](https://user-images.githubusercontent.com/59567959/115285602-575a7880-a14e-11eb-84c8-cc2491db957f.png)
