### ISSUE TITLE
Frsky X8R smart port

### ISSUE THREAD

**Issue by asangag** [zs6buj/AntTracker#37]
Hi

Thanks for developing this tracker &  the support you provide.  I read your RC group thread and still a little bit confused  most probably due to my lack on knowledge in this area! 

If I'm to use X8R receiver and feed telemetry data from FC  to smart port and then receive that on either my taranis or jumper T16 can I then extract telemetry data (what's required for the tracker ) through one of the pins in the module bay  on the back of either radio ? 

If so do I need  5V to 3.3V level converter  ? 

Thanks

**Comment by asangag** [comment]
> Hi asangag,
> Yes you can take 3.3v telemetry from the back bay of a Taranis or similar rc controller directly into the AntTracker.
> 
> You could also use an ESP32 board with [this firmware](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth) to relay BT or WiFi telemetry to the Tracker. The ESP would be mounted on the back of your Jumper.

Thanks. On  the air side  if I use Matek 405-wing with Ardupilot  then do I have to use an inverter (bidirectional  or single) ?

**Comment by zs6buj** [comment]
First of all, if you are using S.Port, on the X8R, then it is inverted (idle low) with reference to a "regular" uart signal, which is idle high.  (If you ever use the F.Port on one of the newer FrSky receivers, it is NOT inverted).  

I'm afraid I don't have much experience with F405 telemetry, but I do know that some uarts on many F405 boards can invert the the signal and convert to one-wire. If you are using BetaFlight, there are some telemery settings and CLI commands that must be executed, and it can be be quite tricky. [Here](https://www.youtube.com/watch?v=jT4vf6575TM&ab_channel=JoshuaBardwell) is a YouTube video you might find useful.

**Comment by asangag** [comment]
thanks a lot for your quick response! I have a X8R with a hacked S.Port , so I can use that receiver which can take either inverted or non-inverted signal  to test if I can get telemetry out from F405.  Do i have to use pass through elementary on Ardupilot ?
sorry about so many questions!

**Comment by asangag** [comment]
Below is the Ardupilot configuration from matek website

Frsky Smartport Telemetry
non-inverted (hacked) S.Port signal
TX1 pad of F405-WING
SERIAL1_BAUD   57
SERIAL1_OPTIONS  7
SERIAL1_PROTOCOL  4  or 10(for yaapu)
or TX6 pad of F405-WING
SERIAL6_BAUD   57
SERIAL6_OPTIONS  7
SERIAL6_PROTOCOL  4  or 10(for yaapu)
CRSF

**Comment by zs6buj** [comment]
Ok, I didn't realize you were on Ardupilot.  You would use protocol = 10

**Comment by zs6buj** [comment]
Sounds a bit strange. I believe the board has an accelerometer, so you should also get attitude (x,y,z) data. I have not (yet) tried APM on an F405 stack like the Matek, but I have a little 5" racer with a Mamba F405 and Betaflight.  It does not have a  magnetometer/compass or a barometer (for altitude).

For tracking you need GPS co-ordinates and altitude, but then you want a compass on the tracker box to orientate it to the world co-ordinates around you.

**Comment by asangag** [comment]
Yes the F405-wing board has accelerometer & barometer and  for protocol 4, I get altitude, X,Y,Z data  but not for protocol 10. is there a disadvantage to using protocol 4 over 10 ?  Since 4 is working I guess I can use it like that.

**Comment by zs6buj** [comment]
You can use protocol 4 for the tracker. I originally coded for it, but only recently tested it with pan-sattan. It seems to be ok now.

yaapu has a very nice GUI lua script  for the transmitters, including the Jumpers, but his scripts expects to see protocol 10.

**Comment by asangag** [comment]
looks like I  won't be able to use yaapu then...damn!  but my main objective is to use the tracker and its good to know it works with protocol 4,  do i need an inverter between taranis and tracker  ?

**Comment by zs6buj** [comment]
The tracker has an invert option.

**Comment by asangag** [comment]
I tried so many times  with few DIY inverters and two Receivers with smartport (X8R and R9)  to get protocol 10 but , it just doesn't work. Only  protocol 4 works. But even with protocol 4, I dont know if I'm getting all parameters required for the tracker. what are the mandatory parameters for the tracker to work ?  Then  can check   if I'm receiving them via smartport .

**Comment by zs6buj** [comment]
Ardupilot protocol 10 can be tricky. One issue I found is that it will not simply start sending telemetry without receiving heartbeats (on a different uart of course) from a GCS like Mission Planner.   

Assuming you have a compass on the tracker-box, then
in D-mode (4) we need the following message types

- 0x100 - Altitude
- 0x410 - GPS Status
- 0x800 - GPS co-ordinates

and if you want to fix the home position when the motors are armed

- 0x400 Flight mode and arm_flag

In the tracker activate this debug option to see which message types you are receiving:

#define Debug_FrSkyD_Flight_Mode

If you don't have a compass on the tracker-box, then you need one on the plane, alternatively you can go through a simple procedure to determine the orientation of the tracker box using the GPS co-ordinates only.

**Comment by zs6buj** [comment]
Stale
