### ISSUE TITLE
Porting project to PlatformIO project, as opposed to Arduino IDE

### ISSUE THREAD

**Issue by TTN-** [zs6buj/AntTracker#39]
Would you be open to having this project converted into a PlatformIO project? I'm thinking of doing a fork with exactly that.

https://platformio.org/

It's an extension for Visual Studio Code which makes life a lot easier as a programmer, while still utilizing the arduino framework. Also supports proper debugging on most boards.

**Comment by TTN-** [comment]
Ok so I've made a start, and I can see there has been a LOT of work gone into making this project what it is today.
There's also a fair bit of work in tidying it up splitting the headers into .cpp and .h files and just some general house keeping.

**Comment by TTN-** [comment]
https://github.com/TTN-/AntTracker

**Comment by zs6buj** [comment]
Good morning TTN.  Yes of course, that would be a nice step forward. Let me know if you have any questions. I'm working from my mobile for the next two weeks.

**Comment by TTN-** [comment]
Good morning to you too ZS6buj,

Haha, I know the feeling, got side tracked into this! Alright well I'm working on it, might be a few days till I come out with something functional, did you get anywhere with what you had? I'm part way through splitting it all up into headers/cpp files. Is it worth sharing?

**Comment by zs6buj** [comment]
Yeah, definitely worth sharing. PIO with included libs is much easier for others to build and flash IMO, and easier to debug.

I got quite far, but then hit some snags with dependencies. Then sidetracked, :)

**Comment by zs6buj** [comment]
no progress on this. Sorry I've been quite busy elsewhere
