### ISSUE TITLE
'HUD_ARROW_OFFSET' was not declared in this scope

### ISSUE THREAD

**Issue by Cyberdemon-23** [zs6buj/AntTracker#41]
S E L E C T   E S P   B O A R D   V A R I A N T   ===================

#define ESP32_Variant     7

Utilities:1440:11: error: 'HUD_ARROW_OFFSET' was not declared in this scope

       if (HUD_ARROW_OFFSET == 999) {

           ^

**Comment by zs6buj** [comment]
Hmm..  I just clean compiled with 

`#define ESP32_Variant     7    // ESP32 Dev Module with ILI9341 2.8" colour TFT SPI 240x320`

Could you try with my config.h, and then compare with yours?

https://drive.google.com/file/d/12Qgt1DqaaUvSx4ZDKbQR8JpJOxqkhh_P/view?usp=sharing

It would be best if you could use the latest source, so we are on the same page.

**Comment by Cyberdemon-23** [comment]
Downloaded the latest source, your config file - is the same error. Where is HUD_ARROW_OFFSET written? Maybe the wrong library is being used?

**Comment by zs6buj** [comment]
It would be best if you could use the latest source, so we are on the same page. **V2.19.4**.

HUD is only possible on the large  ILI9341_Display. So in the latest version, Utilities tab, line1249 you will find a block of code to populate/paint the ILI9341_Display pages

` #if  (defined ILI9341_Display)`

and HUD_ARROW_OFFSET is used in this conditional block.

So, its use is predicated on this condition in config.h line 508

`  #if (ESP32_Variant == 7)          // ESP32 Dev Module with ILI9341 2.8" colour TFT SPI 240x320`

In that conditional block we define

`  #define ILI9341_Display         // ILI9341 2.8" COLOUR TFT SPI 240x320 V1.2  `

and then in Utilities, line 1249 we have the conditional block mentioned above

` #if  (defined ILI9341_Display)`

**Comment by zs6buj** [comment]
I see I added that code in V2.18.0. I can check it out a little later.

**Comment by zs6buj** [comment]
When I checked it this morning, it did not compile,  my apologies.  (told myself to go sit in the corner)

It's fixed in V2.19.05.

**Comment by Cyberdemon-23** [comment]
is actually compiling now, but the screen is not displaying anything. See if everything is properly connected
![39249765bc](https://user-images.githubusercontent.com/57357193/148699253-180d37a7-cbee-414f-8a23-eb62de302699.jpg)

**Comment by zs6buj** [comment]
Hmm. I see you have marked the LED pin with 5v, so you know that both Vcc and LED must be powered.

Could you try these pins:

    #define ILI9341_Display         // ILI9341 2.8" COLOUR TFT SPI 240x320 V1.2  
    #define SCLK          18        // blue wire on my test setup
    #define MOSI          23        // yellow wire
    #define CS            25        // white wire
    #define DC            22        // green wire
    #define RST           21        // brown wire

**Comment by zs6buj** [comment]
I just tested it with the original pins, and that also works:

    #define ILI9341_Display         // ILI9341 2.8" COLOUR TFT SPI 240x320 V1.2  
    #define SCLK          18        // blue wire on my test setup
    #define MOSI          23        // yellow wire
    #define CS            25        // white wire
    #define DC            26        // green wire  



    #define RST           27        // brown wire
    // LED=3.3V,  Vcc=5v,  Gnd 
    // MISO                not used by Adafruit     

![image](https://user-images.githubusercontent.com/12892533/148727903-de0fa35f-8d97-4d3e-a883-5bd93fe73191.png)


Could you double check your wiring?

**Comment by zs6buj** [comment]
![image](https://user-images.githubusercontent.com/12892533/148731324-564692fe-1c74-4e6b-8c13-a82a4749dd81.png)

**Comment by zs6buj** [comment]
If you could post the serial monitor log it might be helpful to see if there are any startup anomalies.

**Comment by Cyberdemon-23** [comment]
`13:03:11.540 -> 
13:03:11.540 -> Starting AntTrack version:2.19.05
13:03:12.254 -> Display support activated: Landscape 
13:03:12.254 -> 240x320  text_size=2  char_w_px=12  char_h_px=16  scr_h_ch=15  scr_w_ch=26
13:03:12.348 -> Target Board is Target Board = 3  ESP32 / Variant is Dev Module with ILI9341 2.8in COLOUR TFT SPI
13:03:12.348 -> Serial Telemetry In
13:03:12.348 -> Selected protocol is Mavlink 1
13:03:12.348 -> headingSource = 2 FC Compass
13:03:12.348 -> Servo slowdown factor is 10ms per degree of rotation
13:03:13.275 -> Testing Servos
`

**Comment by Cyberdemon-23** [comment]
```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4
E (147) psram: PSRAM ID read error: 0xffffffff

Starting AntTrack version:2.19.05
Display support activated: Landscape 
240x320  text_size=2  char_w_px=12  char_h_px=16  scr_h_ch=15  scr_w_ch=26
Target Board is Target Board = 3  ESP32 / Variant is Dev Module with ILI9341 2.8in COLOUR TFT SPI
Serial Telemetry In
Selected protocol is Mavlink 1
headingSource = 2 FC Compass
Servo slowdown factor is 10ms per degree of rotation
Testing Servos

```

**Comment by Cyberdemon-23** [comment]
![ww](https://user-images.githubusercontent.com/57357193/148749821-97c2d261-f04a-4019-ac30-f9e96a69c9fb.PNG)

**Comment by zs6buj** [comment]
"E (147) psram: PSRAM ID read error: 0xffffffff"

This looks a bit suspect. I googled it and got this:

"
One of my ESP32-Cam boards has this issue too.
Is the most likely explanation hardware failure of the PSRAM chip?"

The mpu should not hang during "Testing Servos", but you can disable the servo test in config.h

config.h line 109 


`//#define Test_Servos      // Move servos through their limits`

**Comment by zs6buj** [comment]
My bootup looks like this:

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4

Starting AntTrack version:2.19.05
Display support activated: Landscape 
240x320  text_size=2  char_w_px=12  char_h_px=16  scr_h_ch=15  scr_w_ch=26
Target Board is Target Board = 3  ESP32 / Variant is Dev Module with ILI9341 2.8in COLOUR TFT SPI
Serial Telemetry In
Selected protocol is Mavlink 1
headingSource = 2 FC Compass
Servo slowdown factor is 10ms per degree of rotation
Testing Servos

**Comment by Cyberdemon-23** [comment]
Uploaded to another board - this error disappeared, but the screen remained white.
I change
`Adafruit_ILI9341 display = Adafruit_ILI9341 (CS, DC, RST); // LED = 3.3V, Vcc = 5v, Gnd`
on the
`Adafruit_ILI9341 display = Adafruit_ILI9341 (CS, DC, MOSI, SCLK, RST);`
now everything works!

**Comment by zs6buj** [comment]
I'm guessing that I'm one version behind of the Adafruit ILI9341 library.

![image](https://user-images.githubusercontent.com/12892533/148894155-fdc14b61-0528-4855-9aa3-5f145757c66c.png)

**Comment by zs6buj** [comment]
I updated to 1.5.10, but observing the two versions of the object, 

` Adafruit_ILI9341 display = Adafruit_ILI9341(CS, DC, RST);` is far faster. Refresh of the display is very fast, but with 

`Adafruit_ILI9341 display = Adafruit_ILI9341 (CS, DC, MOSI, SCLK, RST);`

refresh is slow. Too slow to refresh to HUD fast enough. I think maybe this version renders the display in main RAM (on the stack), and it is slower. Guessing here.

**Comment by zs6buj** [comment]
First is hardware SPI, and the second is software SPI

**Comment by zs6buj** [comment]
Cool! My pleasure CyberD.
