### ISSUE TITLE
[Feature Request] BLE Support for Telemetry

### ISSUE THREAD

**Issue by Razsmithii** [zs6buj/AntTracker#46]
Ant Tracker seems to be a great and smart solution. What i miss: BLE Support for getting temelemtry Data. When an external TX is connected to taranis X-Lite, there is no easy serial Port available. Why Not usw BLE, like in "Telemetry Viewer" (Smartphone App)?

**Comment by arifly** [comment]
Ive got a modified  version with BLE, Crossfire and Touch working, ..sort of. 
Ive someone is interested i put it on git

**Comment by zs6buj** [comment]
Arifly:

Yes please. That would be a nice feature to add.

**Comment by arifly** [comment]
noob mod: 
[https://github.com/arifly/AntTracker/tree/master/Source/AntTrack](url)
to use with a ESP32 (DevKit), the Frsky X10 Bluetooth Module, OpenTX in Telemetry Mirror Mode and Crossfire (hardcoded atm)

The serviceUUID need to be changed to your devices adress

I will try to make PRs(?)

**Comment by zs6buj** [comment]
Ok, thank you. I'm away from home until early May, but can stay in touch.

**Comment by Razsmithii** [comment]
BLE Connection works great - many thanks!

**Comment by zs6buj** [comment]
That's great news. I'll check this out as soon as I can. I leave for home on Monday.

**Comment by arifly** [comment]
yes, but sometimes the mainloop didn't get time to do his thing.
And the bluetooth-stack can freeze.
To overcome this i use a second ESP with watchdog enabled.
To get away with no PRs, i add a converter to LTM, so nearly no changes to the Original Code are needed :>

As we use HardwareSerial the default speed for LTM can changed to 115200.
Or change the speed in "BLE-crsf2ltm.ino". LTM messages are send as fast as possible. 

[https://github.com/arifly/BLE-crsf2ltm](https://github.com/arifly/BLE-crsf2ltm)
