### ISSUE TITLE
No Header Fioe (.h)

### ISSUE THREAD

**Issue by kusnendar** [zs6buj/AntTracker#50]
Get error not header file (.h) frome new libraries file new version
![IMG_20220901_080414_351](https://user-images.githubusercontent.com/12068892/187811657-3e3802fd-f20d-4c7f-971c-b856ab36cba0.jpg)

**Comment by zs6buj** [comment]
Only copy these folders from my GitHub STMF1xx libraries file. They may
well be out of date, so you might need to use Library Manager in the
Arduino GUI to update them.

[image: image.png]

**Comment by kusnendar** [comment]
> 

I has copy these folder. But same result. & I checked at libraries folder not found file (.h)

**Comment by zs6buj** [comment]
I just compiled it here. I clean compiles, but is too big for flash memory. I guess I added too many "features" into the ESP32 version. Lol.

![image](https://user-images.githubusercontent.com/12892533/187880254-6d60f431-4692-4eec-a01c-c3822478abd8.png)

I'll see if I can cut it down.

So, in YOUR Arduino library folder, delete (or save somewhere  else) all the libraries. Now try to compile, and it will complain about a missing library. Copy back only that library folder.  COPY ONLY THE LIBRARY NAME FOLDER, NOT THE COLLECTIVE FOLDER WITH THEM INSIDE.

You might want to tick "Show verbose output during compilation" in File/Preferences
![image](https://user-images.githubusercontent.com/12892533/187882083-6354970f-0228-42ea-b5be-ada37d81b33b.png)

Read the resulting compilation logs carefully when you try to compile.

**Comment by zs6buj** [comment]
Ok, it clean compiles when I select 128k variant:

![image](https://user-images.githubusercontent.com/12892533/187882990-c69dbc7e-3393-4953-93b9-6f172bcd328c.png)

![image](https://user-images.githubusercontent.com/12892533/187882776-455a3585-9f50-415d-a295-b3726e6d0ede.png)

**Comment by kusnendar** [comment]
> Ok, it clean compiles when I select 128k variant:
> 
> ![image](https://user-images.githubusercontent.com/12892533/187882990-c69dbc7e-3393-4953-93b9-6f172bcd328c.png)
> 
> ![image](https://user-images.githubusercontent.com/12892533/187882776-455a3585-9f50-415d-a295-b3726e6d0ede.png)

Do can i use my bluepill STM22F103C8(64k) for this project?

**Comment by kusnendar** [comment]
> I just compiled it here. I clean compiles, but is too big for flash memory. I guess I added too many "features" into the ESP32 version. Lol.
> 
> ![image](https://user-images.githubusercontent.com/12892533/187880254-6d60f431-4692-4eec-a01c-c3822478abd8.png)
> 
> I'll see if I can cut it down.
> 
> So, in YOUR Arduino library folder, delete (or save somewhere else) all the libraries. Now try to compile, and it will complain about a missing library. Copy back only that library folder. COPY ONLY THE LIBRARY NAME FOLDER, NOT THE COLLECTIVE FOLDER WITH THEM INSIDE.
> 
> You might want to tick "Show verbose output during compilation" in File/Preferences ![image](https://user-images.githubusercontent.com/12892533/187882083-6354970f-0228-42ea-b5be-ada37d81b33b.png)
> 
> Read the resulting compilation logs carefully when you try to compile.

Please show your  libraries folder(take picture)

**Comment by kusnendar** [comment]
> I just compiled it here. I clean compiles, but is too big for flash memory. I guess I added too many "features" into the ESP32 version. Lol.
> 
> ![image](https://user-images.githubusercontent.com/12892533/187880254-6d60f431-4692-4eec-a01c-c3822478abd8.png)
> 
> I'll see if I can cut it down.
> 
> So, in YOUR Arduino library folder, delete (or save somewhere else) all the libraries. Now try to compile, and it will complain about a missing library. Copy back only that library folder. COPY ONLY THE LIBRARY NAME FOLDER, NOT THE COLLECTIVE FOLDER WITH THEM INSIDE.
> 
> You might want to tick "Show verbose output during compilation" in File/Preferences ![image](https://user-images.githubusercontent.com/12892533/187882083-6354970f-0228-42ea-b5be-ada37d81b33b.png)
> 
> Read the resulting compilation logs carefully when you try to compile.

I hope your make 2 file config for STM32 (64k) & ESP32

**Comment by zs6buj** [comment]
Ok, but my library folder has many libraries, also for other boards. Also, be aware that every board type has its own package folders, which contain libraries for those board variants:
![image](https://user-images.githubusercontent.com/12892533/187892353-978ee302-052d-4bcb-9100-5519decac169.png)

![image](https://user-images.githubusercontent.com/12892533/187892537-54cc80e9-9076-49a6-b2e4-93ed59810f92.png)

**Comment by zs6buj** [comment]
You can put library folders into Documents/arduino/libraries/

and the IDE usually looks around for the best ones

**Comment by zs6buj** [comment]
Do NOT put folder hierarchies in there

**Comment by zs6buj** [comment]
I also cleaned up the version numbers slightly on GitHub, but you should not need to download new version 2.19.09

**Comment by zs6buj** [comment]
Stale
