### ISSUE TITLE
Express LRS

### ISSUE THREAD

**Issue by asangag** [zs6buj/AntTracker#52]
will this tracker work with ELRS protocol and ardupilot FC ?

cheers

**Comment by zs6buj** [comment]
@asangag 

Regretfully, not yet, and I'm pretty tied up with other things right now

Perhaps one of the Beteflight devs would like to do a PR. All we need is GPS co-ordinates and altitude above ground.

**Comment by asangag** [comment]
thanks....hopefully some dev will take on the task  as ELRS is getting very popular  :)
