### ISSUE TITLE
Missing Library QMC5883LCompass

### ISSUE THREAD

**Issue by K1rdro** [zs6buj/AntTracker#65]
It looks like the library for QMC5883LCompass is not included in the libraries folder. There is one in the esp32 folder, but it's for QMC5883L, while source/stable/v2.20.04/AntTrack/Compass.ino includes QMC5883LCompass.h. Is it this one: [QMC5883LCompass](https://github.com/mprograms/QMC5883LCompass)?

**Comment by zs6buj** [comment]
K1dro:

Thanks for the feedback. For convenience I have added the "QMC5883LCompass" library into the All and the ESP32 folders, and kept the older "QMC5883L" library for backward compatibility.
