### ISSUE TITLE
Continuous Rotation Servo 360

### ISSUE THREAD

**Issue by HKR1987** [zs6buj/AntTracker#74]
Hi,
it is possible to use Continuous Rotation Servo 360 as azimuth servo?
When i try it, it rotate too much

**Comment by zs6buj** [comment]
You can not use a continuous rotation azimuth servo turntable unless it is accompanied by electronics and a rotation angle sensor. It has to be smart enough to turn to an angle and stop there. Google this.

**Comment by pki791** [comment]
@zs6buj this can be done using the mag, maybe it would be possible to implement this? i build my tracker as multiturn and have no way to get a fixed position without mag.

**Comment by zs6buj** [comment]
If you switch to stepper motors it solves this problem. Or just 1 stepper to drive the azimuth platter. With steppers I can set an arbitrary zero point, or remember any position and return to it

**Comment by pki791** [comment]
Stepper is not a solution for my tracker. For the use of mag and servo it would be:
- read mag via i2c (5883)
- calibration routine (30 seconds of turning in one side)
- simple routine to follow the sensor where about 1500 would mean stop, lower values rotation left, higher values rotation right.
