### ISSUE TITLE
T-Display ESP32 1.14" - Problems

### ISSUE THREAD

**Issue by samnikos7** [zs6buj/AntTracker#77]
I have various problems with TTGO T-Display ESP32 1.14"

![image](https://github.com/zs6buj/AntTracker/assets/87907405/4843ed0e-a885-4d2e-94ab-11c6270a7fec)

With v2.21.02 (esp boards v2.0.16 - v2.0.17)
- Unable to connect to my HM-10 bluetooth SLAVE giving its name in #define BT_MODE  1 (Master Mode).
- I get errors compiling the sketch when I try to #define BT_MODE  2 (Slave Mode)

![image](https://github.com/zs6buj/AntTracker/assets/87907405/200ee15b-df98-4d6c-b93a-47e9333134a9)

With the latest version v2.21.04 (updated libraries + esp boards v3.0.0).
- The display is always OFF, but serial monitor is working in IDE.
- Unable to connect to my HM-10 bluetooth SLAVE giving its name in #define BT_MODE  1 (Master Mode).

**Comment by zs6buj** [comment]
[samnikos7](https://github.com/samnikos7)

It turns out the new ESP32 core 3.0.0 breaks TFT_eSPI. So please go back to core 2.0.17 for the time being.

![image](https://github.com/zs6buj/AntTracker/assets/12892533/ca8a14b5-1678-41ac-b6b7-ef0739b10938)

Also, please use tracker v2.21.05 on my git. I changed something in the uart code flow.

**Comment by samnikos7** [comment]
Thank you a lot for your quick reply.
- I rolled back to esp32 core v2.0.17, I used tracker v2.21.05 and my TTGO T-Display ESP32 1.14" is working now.
- Bluetooth Module HM-10 is still unable to connect with the ESP. 
- Another Bluetooth Module HC-05 is connecting normally as SLAVE but I would like to use my internal Radiomaster TX16S RF-BM-S02 Bluetooth Module (CC2540 similar to HM-10) as Telemetry. I had no problems using with u360gts.   
https://www.instructables.com/Bluetooth-on-Radiomaster-TX16S/
- When I try to compile with "#define WIFI_PROTOCOL 2    // UDP"  I get errors.
![image](https://github.com/zs6buj/AntTracker/assets/87907405/6f52e338-6b76-48bd-a8f6-eb21d7aa0cd9)

Is it possible to use Bluetooth as Telemetry IN and Wifi AP as Telemetry MIRROR for other use (like Telemetry Viewer for Android) at the same time?

**Comment by zs6buj** [comment]
Thank you again for the feedback. It is invaluable as I am rather time constrained here. 

Unfortunately the HM-10 uses  BLE, Bluetooth 4.0, and I have not yet upgraded the tracker code for BLE support. It's one of the things on the ToDo list. 

Could you please post a copy of your config.h

With the correct settings, [mav2pt](https://github.com/zs6buj/mav2pt/wiki) will switch BT (Classic) to WiFi UDP.

**Comment by samnikos7** [comment]
I will try to compile it with multiple combinations (e.g BT as SLAVE, WIFI STA->AP, all protocols one by one, etc) and post the results later.
Here is my current [config.h.txt](https://github.com/user-attachments/files/15613203/config.h.txt) with many complication errors, many Functions from the other *ino files seem to be "not declared in this scope" in the main void loop.

**Comment by zs6buj** [comment]
Hold fire for now :) I'm going through all Media, all protocols at present. I'll upload when I'm ready

**Comment by zs6buj** [comment]
try v 2.21.06. I have to go fetch my granddaughter and take her to swimming lessons :)

**Comment by samnikos7** [comment]
I've just tried v2.21.06 with no complication errors choosing "#define MEDIUM_IN  2    // WiFi - ESP only" choosing every PROTOCOL (1-9) but get bootloops like this.

![image](https://github.com/zs6buj/AntTracker/assets/87907405/0d711b0f-95b9-4e83-93a8-d850895edb8a)

When I choose "#define PROTOCOL 0     // AUTO detect protocol" with excact the same settings I get complication errors.

![image](https://github.com/zs6buj/AntTracker/assets/87907405/5179e331-01e4-4c20-bc45-5b645b00b422)

**Comment by zs6buj** [comment]
Ok, thank you

**Comment by zs6buj** [comment]
I have posted V 2.21.07 |(under release_candidate) with fixes and some new features. Please could you check it when you get the chance.

**Comment by zs6buj** [comment]
Also check out [https://github.com/zs6buj/CRSF_Utlilties](url) where you will find three utilities for CRSF to send telemetry from uart to UDP or BT, and read UDP. The utilities work with AntTrack.
