### ISSUE TITLE
[Support] What stepper motor and driver do you recommend to use?

### ISSUE THREAD

**Issue by DiscoMan18** [zs6buj/AntTracker#82]
With your tracker. Thanks!

**Comment by zs6buj** [comment]
Hello, I did all my testing with a pair of Nema17 steppers, incorporating a 10x reduction gearbox and two TB6600 drivers.  This is moderately large and powerful, with 4kg/cm torque. Your requirement will depend on the size and mass of your antenna. Google Nema and go take a look there at what is available. The principles remain the same for all bi-polar steppers, so shop around.

To be honest I have not had the time to research stepper mechanicals for an antenna tracker. You would probably want a platter driven by the azimuth stepper, with the elevation stepper mounted on top with appropriate hardware.
