### ISSUE TITLE
fixed wing heading

### ISSUE THREAD

**Issue by marcogarzotti** [zs6buj/AntTracker#9]
First of all: nice job!
Second: i don't know if you are aware of that but it's quite common for a fixed wing to use gps module without compass (or with compass not wired). With this kind of setup the heading on the ground is not reliable at all.
Is it possible to define the GS heading by placing the aircraft as close as possible to the GS, then press the button to record the home point, then move the aircraft few (10) meters in the right direction, and then press the button again to calculate the heading?
Thanks.

**Comment by zs6buj** [comment]
Hi marcogarzotti 

If you look in the Wiki,under Positioning The Antenna,  you will see

2) GPS - use this if your craft has a GPS, but no FC or compass

Position the tracker box such that the antenna faces the field straight ahead. Power up
the craft and tracker, and wait for a good GPS lock. The tracker's LED will flash fast. 
Walk several metres (say 5) straight ahead with the craft, place it on the ground, 
return and press the Set_Home button. The tracker calculates the compass direction of a 
vector (line) from where the craft was at the first GPS lock, to where it was when the 
Set_Home button was pressed, then use as the assumed direction of the tracker antenna. 

  Before you build/compile the tracker firmware, be sure to un-comment the appropriate 
  #define macro according to your choice of heading source:

  #define Heading_Source   1  // GPS 
  //#define Heading_Source   2  // Flight Computer 
 // #define Heading_Source   3  // Tracker_Compass   

Good luck
Eric
